import { getFirebaseDatabase, fetchBoxLocationOnce } from './firebaseClient';
import { onValue, off, ref, set, serverTimestamp, get } from 'firebase/database';
import { setSmartBoxAssignedUser, supabase } from './supabaseClient';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { AppState, type NativeEventSubscription } from 'react-native';
import { calculateDistanceMeters } from '../utils/geoUtils';
import * as Location from 'expo-location';

export type PairingMode = 'ONE_TIME' | 'SESSION';
export type PairingStatus = 'ACTIVE' | 'EXPIRED' | 'REVOKED';

export interface BoxPairingState {
    box_id: string;
    rider_id: string;
    mode: PairingMode;
    status: PairingStatus;
    pair_token?: string;
    paired_at?: number;
    expires_at?: number;
    max_uses?: number;
    uses?: number;
    last_updated?: number;
}

export interface PairingQrPayload {
    boxId: string;
    token?: string;
    mode?: PairingMode;
    sessionHours?: number;
}

/** Callback fired when a pairing is about to expire, has expired, or drift is detected. */
export type ExpirationWarningCallback = (event: {
    type: 'WARNING' | 'EXPIRED' | 'DRIFT_WARNING' | 'DRIFT_EXPIRED';
    boxId: string;
    riderId: string;
    remainingMs: number;
    /** Distance in meters between rider and box (only for DRIFT_* events). */
    distanceMeters?: number;
}) => void;

const DEFAULT_SESSION_HOURS = 24;
const PAIRED_BOX_CACHE_KEY_PREFIX = 'parcelSafe:lastPairedBoxId:';
/** How often the background monitor checks expiration (ms). */
const EXPIRATION_CHECK_INTERVAL_MS = 60_000; // 1 minute
/** Warn the rider this many ms before expiration. */
const EXPIRATION_WARNING_THRESHOLD_MS = 30 * 60 * 1000; // 30 minutes

// ======================== Proximity Safeguard Constants ========================

/** Maximum distance (meters) between rider and box to allow pairing. */
export const PAIRING_MAX_DISTANCE_M = 500;

/** Warn when rider and box drift apart by this distance (meters). */
export const DRIFT_WARNING_THRESHOLD_M = 5_000; // 5 km

/** Auto-unpair when rider and box are this far apart (meters). */
export const DRIFT_UNPAIR_THRESHOLD_M = 50_000; // 50 km

/** Number of consecutive checks exceeding the unpair threshold before acting. */
const DRIFT_SUSTAINED_CHECKS = 3;

function isValidFirebaseKeySegment(value: string): boolean {
    // RTDB disallows: . # $ [ ] /
    // Also avoid empty segments.
    return value.length > 0 && !/[.#$\[\]\/]/.test(value);
}

function parseAsPairingQueryString(query: string): PairingQrPayload | null {
    const params = new URLSearchParams(query.startsWith('?') ? query.slice(1) : query);
    const boxId = params.get('boxId') || params.get('box_id');
    if (!boxId) return null;

    const modeRaw = params.get('mode');
    const mode = (modeRaw === 'ONE_TIME' || modeRaw === 'SESSION') ? (modeRaw as PairingMode) : undefined;
    const sessionHoursRaw = params.get('sessionHours');
    const sessionHours = sessionHoursRaw ? Number(sessionHoursRaw) : undefined;

    return {
        boxId,
        token: params.get('token') ?? undefined,
        mode,
        sessionHours: Number.isFinite(sessionHours) ? sessionHours : undefined,
    };
}

export function parsePairingQr(payload: string): PairingQrPayload | null {
    if (!payload || typeof payload !== 'string') {
        return null;
    }

    const trimmed = payload.trim();
    if (!trimmed) return null;

    // JSON payload
    if (trimmed.startsWith('{')) {
        try {
            const data = JSON.parse(trimmed);
            if (data?.boxId || data?.box_id) {
                return {
                    boxId: data.boxId ?? data.box_id,
                    token: data.token ?? data.pairToken,
                    mode: data.mode,
                    sessionHours: data.sessionHours,
                };
            }
        } catch {
            // Fall through to URL parsing
        }
    }

    // Custom scheme payload generated by web: parcelsafe://pair?boxId=...&token=...&mode=...
    // Some RN runtimes can throw on new URL(custom-scheme), so parse the querystring manually first.
    const queryIndex = trimmed.indexOf('?');
    if (queryIndex !== -1) {
        const query = trimmed.slice(queryIndex + 1);
        const parsedQuery = parseAsPairingQueryString(query);
        if (parsedQuery?.boxId) {
            return parsedQuery;
        }
    }

    // URL payload: parcelsafe://pair?boxId=BOX_001&token=abc&mode=SESSION&sessionHours=24
    try {
        const url = new URL(trimmed);
        const boxId = url.searchParams.get('boxId') || url.searchParams.get('box_id');
        if (boxId) {
            const mode = url.searchParams.get('mode') as PairingMode | null;
            const sessionHours = url.searchParams.get('sessionHours');
            return {
                boxId,
                token: url.searchParams.get('token') ?? undefined,
                mode: mode ?? undefined,
                sessionHours: sessionHours ? Number(sessionHours) : undefined,
            };
        }
    } catch {
        // Not a URL
    }

    // Fallback: plain box ID
    // Only accept safe-looking IDs; do NOT treat full URLs as IDs.
    if (isValidFirebaseKeySegment(trimmed) && !/[?&=]/.test(trimmed)) {
        return { boxId: trimmed };
    }

    return null;
}

export function subscribeToRiderPairing(
    riderId: string,
    callback: (state: BoxPairingState | null) => void
): () => void {
    const db = getFirebaseDatabase();
    const pairingRef = ref(db, `riders/${riderId}/pairing`);

    let fallbackUnsubscribe: (() => void) | null = null;
    let usingFallback = false;

    const attachFallbackIfAvailable = async () => {
        if (usingFallback) return;
        usingFallback = true;

        try {
            const cachedBoxId = await AsyncStorage.getItem(`${PAIRED_BOX_CACHE_KEY_PREFIX}${riderId}`);
            if (!cachedBoxId) {
                callback(null);
                return;
            }

            const boxPairingRef = ref(db, `pairings/${cachedBoxId}`);
            fallbackUnsubscribe = onValue(
                boxPairingRef,
                (snapshot) => {
                    const data = snapshot.val() as BoxPairingState | null;
                    if (data && data.rider_id === riderId) {
                        callback(data);
                    } else {
                        callback(null);
                    }
                },
                () => {
                    callback(null);
                }
            );
        } catch {
            callback(null);
        }
    };

    const unsubscribe = onValue(
        pairingRef,
        (snapshot) => {
            const data = snapshot.val() as BoxPairingState | null;
            if (data) {
                // Prefer rider-scoped pairing when present.
                callback(data);
                if (fallbackUnsubscribe) {
                    fallbackUnsubscribe();
                    fallbackUnsubscribe = null;
                }
                return;
            }

            // If the rider-scoped node is empty (for any reason), try falling back to /pairings/{cachedBoxId}.
            void attachFallbackIfAvailable();
        },
        () => {
            // Permission/network cancellation callback
            void attachFallbackIfAvailable();
        }
    );

    return () => {
        try {
            unsubscribe();
        } catch {
            off(pairingRef);
        }
        if (fallbackUnsubscribe) {
            try {
                fallbackUnsubscribe();
            } catch {
                // ignore
            }
        }
    };
}

export function subscribeToBoxPairing(
    boxId: string,
    callback: (state: BoxPairingState | null) => void
): () => void {
    const db = getFirebaseDatabase();
    const pairingRef = ref(db, `pairings/${boxId}`);

    const unsubscribe = onValue(pairingRef, (snapshot) => {
        const data = snapshot.val();
        callback((data as BoxPairingState) || null);
    });

    return () => off(pairingRef);
}

// ======================== Proximity Validation ========================

/**
 * Validate that a rider is physically close to the box before pairing.
 *
 * @returns The distance in meters between rider and box.
 * @throws Error if the rider is too far from the box (> PAIRING_MAX_DISTANCE_M).
 */
export async function validatePairingProximity(
    riderLat: number,
    riderLng: number,
    boxId: string,
): Promise<number> {
    const boxLocation = await fetchBoxLocationOnce(boxId);

    // Box has never reported any location — can't validate.
    // Allow pairing (box may be new / never powered on).
    if (!boxLocation) {
        console.log('[Pairing] No box location data available, skipping proximity check');
        return 0;
    }

    const distanceM = calculateDistanceMeters(
        riderLat, riderLng,
        boxLocation.latitude, boxLocation.longitude,
    );

    if (distanceM > PAIRING_MAX_DISTANCE_M) {
        const distKm = (distanceM / 1000).toFixed(1);
        throw new Error(
            `You're too far from this box (${distKm} km away). ` +
            `You need to be within ${PAIRING_MAX_DISTANCE_M}m to pair.`
        );
    }

    return distanceM;
}

export async function pairBoxWithRider(params: {
    boxId: string;
    riderId: string;
    mode: PairingMode;
    pairToken?: string;
    sessionHours?: number;
    /** Rider's current GPS, used for proximity check. Omit to skip. */
    riderLocation?: { latitude: number; longitude: number };
    /** Skip proximity check (for admin remote-pairing). */
    skipProximityCheck?: boolean;
}): Promise<void> {
    const { boxId, riderId, mode, pairToken, sessionHours, riderLocation, skipProximityCheck } = params;

    if (!boxId || typeof boxId !== 'string' || !isValidFirebaseKeySegment(boxId)) {
        throw new Error('Invalid boxId for pairing');
    }

    if (!riderId || typeof riderId !== 'string' || !isValidFirebaseKeySegment(riderId)) {
        throw new Error('Invalid riderId for pairing');
    }

    if (mode !== 'ONE_TIME' && mode !== 'SESSION') {
        throw new Error('Invalid pairing mode');
    }

    if (mode === 'SESSION') {
        const hours = sessionHours ?? DEFAULT_SESSION_HOURS;
        if (!Number.isFinite(hours) || hours <= 0) {
            throw new Error('Invalid session duration');
        }
    }

    // Safeguard 1: Proximity check
    if (riderLocation && !skipProximityCheck) {
        await validatePairingProximity(
            riderLocation.latitude,
            riderLocation.longitude,
            boxId,
        );
    }

    const db = getFirebaseDatabase();
    const now = Date.now();
    const expiresAt = mode === 'SESSION'
        ? now + (sessionHours ?? DEFAULT_SESSION_HOURS) * 60 * 60 * 1000
        : undefined;

    // IMPORTANT: Firebase RTDB `set()` rejects `undefined` values anywhere in the object.
    // Build a payload that omits optional keys unless they have a real value.
    const pairingPayload: BoxPairingState = {
        box_id: boxId,
        rider_id: riderId,
        mode,
        status: 'ACTIVE',
        paired_at: now,
        uses: 0,
        last_updated: now,
        ...(pairToken ? { pair_token: pairToken } : {}),
        ...(expiresAt ? { expires_at: expiresAt } : {}),
        ...(mode === 'ONE_TIME' ? { max_uses: 1 } : {}),
    };

    await set(ref(db, `pairings/${boxId}`), {
        ...pairingPayload,
        last_updated: serverTimestamp(),
    });

    await set(ref(db, `riders/${riderId}/pairing`), {
        ...pairingPayload,
        last_updated: serverTimestamp(),
    });

    // Cache last paired box for cross-screen fallback.
    try {
        await AsyncStorage.setItem(`${PAIRED_BOX_CACHE_KEY_PREFIX}${riderId}`, boxId);
    } catch {
        // ignore
    }

    // Best-effort: reflect assignment in Supabase so other UIs don't show "Unassigned".
    // Ignore failures (RLS / offline) since the source of truth remains RTDB pairing state.
    try {
        await setSmartBoxAssignedUser(boxId, riderId);
    } catch {
        // ignore
    }
}

export async function revokePairing(boxId: string, riderId: string): Promise<void> {
    const db = getFirebaseDatabase();
    const now = Date.now();

    const revokedState: Partial<BoxPairingState> = {
        status: 'REVOKED',
        last_updated: now,
    };

    await set(ref(db, `pairings/${boxId}`), {
        ...revokedState,
        last_updated: serverTimestamp(),
    });

    await set(ref(db, `riders/${riderId}/pairing`), {
        ...revokedState,
        last_updated: serverTimestamp(),
    });
}

export function isPairingActive(state: BoxPairingState | null): boolean {
    return !!state && state.status === 'ACTIVE';
}

// ========================== Auto-Expiration Helpers ==========================

/**
 * Mark a pairing as EXPIRED in both `/pairings/{boxId}` and
 * `/riders/{riderId}/pairing`.  Also clears the Supabase `currentRiderId`
 * assignment so the admin dashboard stays up-to-date.
 *
 * This is idempotent -- calling it multiple times is harmless.
 */
export async function markPairingExpired(boxId: string, riderId: string): Promise<void> {
    try {
        const db = getFirebaseDatabase();
        const now = Date.now();

        // Only update if the pairing is still ACTIVE (avoids overwriting a REVOKED state).
        const pairingSnap = await get(ref(db, `pairings/${boxId}`));
        const current = pairingSnap.val() as BoxPairingState | null;
        if (!current || current.status !== 'ACTIVE') return;

        const expiredPayload = {
            status: 'EXPIRED' as const,
            expired_at: now,
            last_updated: serverTimestamp(),
        };

        await set(ref(db, `pairings/${boxId}`), { ...current, ...expiredPayload });
        await set(ref(db, `riders/${riderId}/pairing`), { ...current, ...expiredPayload });

        // Best-effort: clear Supabase assignment.
        try {
            await setSmartBoxAssignedUser(boxId, null);
        } catch {
            // Supabase may be offline -- tolerable since Firebase is source of truth.
        }

        // Clear cached pairing so other screens know the rider is no longer paired.
        try {
            await AsyncStorage.removeItem(`${PAIRED_BOX_CACHE_KEY_PREFIX}${riderId}`);
        } catch {
            // ignore
        }

        console.log(`[Pairing] Marked pairing EXPIRED: box=${boxId} rider=${riderId}`);
    } catch (error) {
        // Non-critical -- the next check will retry.
        console.warn('[Pairing] Failed to mark expired:', error);
    }
}

// ======================== Background Expiration Monitor ========================

let _monitorTimer: ReturnType<typeof setInterval> | null = null;
let _monitorRiderId: string | null = null;
let _monitorAppStateSub: NativeEventSubscription | null = null;
let _expirationWarningCb: ExpirationWarningCallback | null = null;

/**
 * Start a background monitor that periodically checks the rider's active
 * pairing and automatically marks it EXPIRED when the session elapses.
 *
 * It also fires an `ExpirationWarningCallback` 30 minutes before expiry so
 * the UI can alert the rider.
 *
 * Safeguard 2: Additionally checks the distance between the rider's phone GPS
 * and the box's last known GPS. Warns at 5 km and auto-unpairs at 50 km if
 * sustained for 3 consecutive checks.
 *
 * Call `stopPairingExpirationMonitor()` (or pass a different riderId) to stop.
 */
export function startPairingExpirationMonitor(
    riderId: string,
    onWarning?: ExpirationWarningCallback,
): void {
    // Avoid duplicate monitors for the same rider.
    if (_monitorTimer && _monitorRiderId === riderId) return;
    stopPairingExpirationMonitor();

    _monitorRiderId = riderId;
    _expirationWarningCb = onWarning ?? null;

    // Safeguard 2: Track consecutive drift violations
    let consecutiveDriftViolations = 0;

    const checkExpiration = async () => {
        try {
            const db = getFirebaseDatabase();
            const snap = await get(ref(db, `riders/${riderId}/pairing`));
            const state = snap.val() as BoxPairingState | null;

            if (!state || state.status !== 'ACTIVE') return;

            const now = Date.now();

            // ---- Session Expiration Check ----
            if (state.expires_at) {
                const remaining = state.expires_at - now;

                if (remaining <= 0) {
                    // Check if rider is currently completing a delivery with THIS box
                    let hasActiveDelivery = false;
                    try {
                        const { data, error } = await supabase
                            .from('deliveries')
                            .select('id')
                            .eq('rider_id', riderId)
                            .eq('box_id', state.box_id)
                            .in('status', ['ASSIGNED', 'IN_TRANSIT', 'ARRIVED'])
                            .limit(1);

                        if (!error && data && data.length > 0) {
                            hasActiveDelivery = true;
                        }
                    } catch (err) {
                        console.warn('[Pairing] Could not verify active deliveries, assuming none.', err);
                    }

                    if (hasActiveDelivery) {
                        // Defer expiration until delivery completes, warn UI playfully
                        _expirationWarningCb?.({
                            type: 'WARNING',
                            boxId: state.box_id,
                            riderId,
                            remainingMs: 0,
                        });
                        return;
                    }

                    // Session expired -- mark it.
                    await markPairingExpired(state.box_id, riderId);
                    _expirationWarningCb?.({
                        type: 'EXPIRED',
                        boxId: state.box_id,
                        riderId,
                        remainingMs: 0,
                    });
                    return; // No need to check drift if already expired
                } else if (remaining <= EXPIRATION_WARNING_THRESHOLD_MS) {
                    _expirationWarningCb?.({
                        type: 'WARNING',
                        boxId: state.box_id,
                        riderId,
                        remainingMs: remaining,
                    });
                }
            }

            // ---- Safeguard 2: Drift Detection ----
            try {
                // Use getLastKnownPositionAsync — cheap, no fresh GPS fix needed
                const riderPos = await Location.getLastKnownPositionAsync();
                if (!riderPos) return; // Can't check without rider GPS

                const boxLocation = await fetchBoxLocationOnce(state.box_id);
                if (!boxLocation) return; // Box has never reported GPS

                const distanceM = calculateDistanceMeters(
                    riderPos.coords.latitude, riderPos.coords.longitude,
                    boxLocation.latitude, boxLocation.longitude,
                );

                if (distanceM > DRIFT_UNPAIR_THRESHOLD_M) {
                    consecutiveDriftViolations++;
                    console.warn(
                        `[Pairing] Drift detected: ${(distanceM / 1000).toFixed(1)} km apart ` +
                        `(${consecutiveDriftViolations}/${DRIFT_SUSTAINED_CHECKS} checks)`
                    );

                    if (consecutiveDriftViolations >= DRIFT_SUSTAINED_CHECKS) {
                        // Sustained extreme drift — auto-unpair
                        await markPairingExpired(state.box_id, riderId);
                        _expirationWarningCb?.({
                            type: 'DRIFT_EXPIRED',
                            boxId: state.box_id,
                            riderId,
                            remainingMs: 0,
                            distanceMeters: Math.round(distanceM),
                        });
                        consecutiveDriftViolations = 0;
                    } else {
                        _expirationWarningCb?.({
                            type: 'DRIFT_WARNING',
                            boxId: state.box_id,
                            riderId,
                            remainingMs: 0,
                            distanceMeters: Math.round(distanceM),
                        });
                    }
                } else if (distanceM > DRIFT_WARNING_THRESHOLD_M) {
                    // Soft warning zone — don't increment unpair counter
                    _expirationWarningCb?.({
                        type: 'DRIFT_WARNING',
                        boxId: state.box_id,
                        riderId,
                        remainingMs: 0,
                        distanceMeters: Math.round(distanceM),
                    });
                    // Reset unpair counter since we're in warning zone, not critical
                    consecutiveDriftViolations = 0;
                } else {
                    // Distance is healthy — reset counters
                    consecutiveDriftViolations = 0;
                }
            } catch (driftErr) {
                // Drift check is non-critical; never block the expiration monitor
                console.warn('[Pairing] Drift check failed (non-critical):', driftErr);
            }
        } catch {
            // Swallow -- will retry next interval.
        }
    };

    // Run immediately, then on interval.
    void checkExpiration();
    _monitorTimer = setInterval(checkExpiration, EXPIRATION_CHECK_INTERVAL_MS);

    // Also check whenever the app returns to the foreground (phone may have
    // been asleep for hours).
    _monitorAppStateSub = AppState.addEventListener('change', (nextState) => {
        if (nextState === 'active') {
            void checkExpiration();
        }
    });
}

/** Stop the background expiration monitor. */
export function stopPairingExpirationMonitor(): void {
    if (_monitorTimer) {
        clearInterval(_monitorTimer);
        _monitorTimer = null;
    }
    if (_monitorAppStateSub) {
        _monitorAppStateSub.remove();
        _monitorAppStateSub = null;
    }
    _monitorRiderId = null;
    _expirationWarningCb = null;
}

/**
 * Convenience: returns the milliseconds remaining until the pairing expires,
 * or `null` if there is no expiration (ONE_TIME mode or no active pairing).
 */
export function getPairingRemainingMs(state: BoxPairingState | null): number | null {
    if (!state || state.status !== 'ACTIVE' || !state.expires_at) return null;
    const remaining = state.expires_at - Date.now();
    return remaining > 0 ? remaining : 0;
}

/**
 * Format remaining time as a human-readable string, e.g. "2h 15m" or "< 1 min".
 */
export function formatRemainingTime(ms: number | null): string {
    if (ms === null || ms <= 0) return 'Expired';
    const totalMinutes = Math.ceil(ms / 60_000);
    if (totalMinutes < 1) return '< 1 min';
    const hours = Math.floor(totalMinutes / 60);
    const minutes = totalMinutes % 60;
    if (hours === 0) return `${minutes}m`;
    return minutes > 0 ? `${hours}h ${minutes}m` : `${hours}h`;
}
