import { getFirebaseDatabase } from './firebaseClient';
import { onValue, off, ref, set, serverTimestamp } from 'firebase/database';
import { setSmartBoxAssignedUser } from './supabaseClient';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type PairingMode = 'ONE_TIME' | 'SESSION';
export type PairingStatus = 'ACTIVE' | 'EXPIRED' | 'REVOKED';

export interface BoxPairingState {
    box_id: string;
    rider_id: string;
    mode: PairingMode;
    status: PairingStatus;
    pair_token?: string;
    paired_at?: number;
    expires_at?: number;
    max_uses?: number;
    uses?: number;
    last_updated?: number;
}

export interface PairingQrPayload {
    boxId: string;
    token?: string;
    mode?: PairingMode;
    sessionHours?: number;
}

const DEFAULT_SESSION_HOURS = 24;
const PAIRED_BOX_CACHE_KEY_PREFIX = 'parcelSafe:lastPairedBoxId:';

function isValidFirebaseKeySegment(value: string): boolean {
    // RTDB disallows: . # $ [ ] /
    // Also avoid empty segments.
    return value.length > 0 && !/[.#$\[\]\/]/.test(value);
}

function parseAsPairingQueryString(query: string): PairingQrPayload | null {
    const params = new URLSearchParams(query.startsWith('?') ? query.slice(1) : query);
    const boxId = params.get('boxId') || params.get('box_id');
    if (!boxId) return null;

    const modeRaw = params.get('mode');
    const mode = (modeRaw === 'ONE_TIME' || modeRaw === 'SESSION') ? (modeRaw as PairingMode) : undefined;
    const sessionHoursRaw = params.get('sessionHours');
    const sessionHours = sessionHoursRaw ? Number(sessionHoursRaw) : undefined;

    return {
        boxId,
        token: params.get('token') ?? undefined,
        mode,
        sessionHours: Number.isFinite(sessionHours) ? sessionHours : undefined,
    };
}

export function parsePairingQr(payload: string): PairingQrPayload | null {
    if (!payload || typeof payload !== 'string') {
        return null;
    }

    const trimmed = payload.trim();
    if (!trimmed) return null;

    // JSON payload
    if (trimmed.startsWith('{')) {
        try {
            const data = JSON.parse(trimmed);
            if (data?.boxId || data?.box_id) {
                return {
                    boxId: data.boxId ?? data.box_id,
                    token: data.token ?? data.pairToken,
                    mode: data.mode,
                    sessionHours: data.sessionHours,
                };
            }
        } catch {
            // Fall through to URL parsing
        }
    }

    // Custom scheme payload generated by web: parcelsafe://pair?boxId=...&token=...&mode=...
    // Some RN runtimes can throw on new URL(custom-scheme), so parse the querystring manually first.
    const queryIndex = trimmed.indexOf('?');
    if (queryIndex !== -1) {
        const query = trimmed.slice(queryIndex + 1);
        const parsedQuery = parseAsPairingQueryString(query);
        if (parsedQuery?.boxId) {
            return parsedQuery;
        }
    }

    // URL payload: parcelsafe://pair?boxId=BOX_001&token=abc&mode=SESSION&sessionHours=24
    try {
        const url = new URL(trimmed);
        const boxId = url.searchParams.get('boxId') || url.searchParams.get('box_id');
        if (boxId) {
            const mode = url.searchParams.get('mode') as PairingMode | null;
            const sessionHours = url.searchParams.get('sessionHours');
            return {
                boxId,
                token: url.searchParams.get('token') ?? undefined,
                mode: mode ?? undefined,
                sessionHours: sessionHours ? Number(sessionHours) : undefined,
            };
        }
    } catch {
        // Not a URL
    }

    // Fallback: plain box ID
    // Only accept safe-looking IDs; do NOT treat full URLs as IDs.
    if (isValidFirebaseKeySegment(trimmed) && !/[?&=]/.test(trimmed)) {
        return { boxId: trimmed };
    }

    return null;
}

export function subscribeToRiderPairing(
    riderId: string,
    callback: (state: BoxPairingState | null) => void
): () => void {
    const db = getFirebaseDatabase();
    const pairingRef = ref(db, `riders/${riderId}/pairing`);

    let fallbackUnsubscribe: (() => void) | null = null;
    let usingFallback = false;

    const attachFallbackIfAvailable = async () => {
        if (usingFallback) return;
        usingFallback = true;

        try {
            const cachedBoxId = await AsyncStorage.getItem(`${PAIRED_BOX_CACHE_KEY_PREFIX}${riderId}`);
            if (!cachedBoxId) {
                callback(null);
                return;
            }

            const boxPairingRef = ref(db, `pairings/${cachedBoxId}`);
            fallbackUnsubscribe = onValue(
                boxPairingRef,
                (snapshot) => {
                    const data = snapshot.val() as BoxPairingState | null;
                    if (data && data.rider_id === riderId) {
                        callback(data);
                    } else {
                        callback(null);
                    }
                },
                () => {
                    callback(null);
                }
            );
        } catch {
            callback(null);
        }
    };

    const unsubscribe = onValue(
        pairingRef,
        (snapshot) => {
            const data = snapshot.val() as BoxPairingState | null;
            if (data) {
                // Prefer rider-scoped pairing when present.
                callback(data);
                if (fallbackUnsubscribe) {
                    fallbackUnsubscribe();
                    fallbackUnsubscribe = null;
                }
                return;
            }

            // If the rider-scoped node is empty (for any reason), try falling back to /pairings/{cachedBoxId}.
            void attachFallbackIfAvailable();
        },
        () => {
            // Permission/network cancellation callback
            void attachFallbackIfAvailable();
        }
    );

    return () => {
        try {
            unsubscribe();
        } catch {
            off(pairingRef);
        }
        if (fallbackUnsubscribe) {
            try {
                fallbackUnsubscribe();
            } catch {
                // ignore
            }
        }
    };
}

export function subscribeToBoxPairing(
    boxId: string,
    callback: (state: BoxPairingState | null) => void
): () => void {
    const db = getFirebaseDatabase();
    const pairingRef = ref(db, `pairings/${boxId}`);

    const unsubscribe = onValue(pairingRef, (snapshot) => {
        const data = snapshot.val();
        callback((data as BoxPairingState) || null);
    });

    return () => off(pairingRef);
}

export async function pairBoxWithRider(params: {
    boxId: string;
    riderId: string;
    mode: PairingMode;
    pairToken?: string;
    sessionHours?: number;
}): Promise<void> {
    const { boxId, riderId, mode, pairToken, sessionHours } = params;

    if (!boxId || typeof boxId !== 'string' || !isValidFirebaseKeySegment(boxId)) {
        throw new Error('Invalid boxId for pairing');
    }

    if (!riderId || typeof riderId !== 'string' || !isValidFirebaseKeySegment(riderId)) {
        throw new Error('Invalid riderId for pairing');
    }

    if (mode !== 'ONE_TIME' && mode !== 'SESSION') {
        throw new Error('Invalid pairing mode');
    }

    if (mode === 'SESSION') {
        const hours = sessionHours ?? DEFAULT_SESSION_HOURS;
        if (!Number.isFinite(hours) || hours <= 0) {
            throw new Error('Invalid session duration');
        }
    }

    const db = getFirebaseDatabase();
    const now = Date.now();
    const expiresAt = mode === 'SESSION'
        ? now + (sessionHours ?? DEFAULT_SESSION_HOURS) * 60 * 60 * 1000
        : undefined;

    // IMPORTANT: Firebase RTDB `set()` rejects `undefined` values anywhere in the object.
    // Build a payload that omits optional keys unless they have a real value.
    const pairingPayload: BoxPairingState = {
        box_id: boxId,
        rider_id: riderId,
        mode,
        status: 'ACTIVE',
        paired_at: now,
        uses: 0,
        last_updated: now,
        ...(pairToken ? { pair_token: pairToken } : {}),
        ...(expiresAt ? { expires_at: expiresAt } : {}),
        ...(mode === 'ONE_TIME' ? { max_uses: 1 } : {}),
    };

    await set(ref(db, `pairings/${boxId}`), {
        ...pairingPayload,
        last_updated: serverTimestamp(),
    });

    await set(ref(db, `riders/${riderId}/pairing`), {
        ...pairingPayload,
        last_updated: serverTimestamp(),
    });

    // Cache last paired box for cross-screen fallback.
    try {
        await AsyncStorage.setItem(`${PAIRED_BOX_CACHE_KEY_PREFIX}${riderId}`, boxId);
    } catch {
        // ignore
    }

    // Best-effort: reflect assignment in Supabase so other UIs don't show "Unassigned".
    // Ignore failures (RLS / offline) since the source of truth remains RTDB pairing state.
    try {
        await setSmartBoxAssignedUser(boxId, riderId);
    } catch {
        // ignore
    }
}

export async function revokePairing(boxId: string, riderId: string): Promise<void> {
    const db = getFirebaseDatabase();
    const now = Date.now();

    const revokedState: Partial<BoxPairingState> = {
        status: 'REVOKED',
        last_updated: now,
    };

    await set(ref(db, `pairings/${boxId}`), {
        ...revokedState,
        last_updated: serverTimestamp(),
    });

    await set(ref(db, `riders/${riderId}/pairing`), {
        ...revokedState,
        last_updated: serverTimestamp(),
    });
}

export function isPairingActive(state: BoxPairingState | null): boolean {
    if (!state || state.status !== 'ACTIVE') {
        return false;
    }

    if (state.expires_at && state.expires_at <= Date.now()) {
        return false;
    }

    return true;
}
